### ISSUE TITLE
GBAJS3 (cant save)

### ISSUE THREAD

**Issue by Scribbleyyy** [thenick775/gbajs3#33] opened 2023-12-18 15:47 UTC
So ive been playing pokemon to many types and a few other games but for some reason I just cant save when I close it out
I've downloaded done save states but absolutely nothing works please fix this

**Comment by thenick775** [comment] 2023-12-18 15:52
Have you tried using the "SAVE FILESYSTEM" button with in the `File System` modal?

<img width="325" alt="Screenshot 2023-12-18 at 7 51 19 AM" src="https://github.com/thenick775/gbajs3/assets/40526638/23d7f8b8-eae2-4479-b28b-dbde704be928">

This item is mentioned in the product tour if you re-trigger it from the about modal.

**Comment by thenick775** [comment] 2023-12-24 06:08
I'm going to close this as a dupe of #34, please follow the instructions there, and remember to save your filesystem after any changes such as saving a save state slot, or saving your game!

**Closed by thenick775** 2023-12-24 06:08 UTC
Labels: information requested
